### ISSUE TITLE
bugfix: 0xlindhquist proof is broken

### ISSUE THREAD

**Issue by lsankar4033** [personaelabs/creddd#17]
proof here: https://www.creddd.xyz/user/0xlindhquist

links to an empty page

**Comment by lsankar4033** [comment]
@DanTehrani would you mind taking a look at this? if you don't look at it by thurs, can take a look myself

**Comment by DanTehrani** [comment]
@lsankar4033 
Looks like the database was unavailable for a while. https://vercel.com/personaelabs/cred-frontend/logs?page=2&timeline=maximum&startDate=1696388691438&endDate=1696475091438&selectedLogId=1696462983171220771545837102&selectedLogTimestamp=1696462983171&forceEndDate=1696470458000

It's back now and the page is working but not sure why this happened. 

Now signs of Render being down https://status.render.com/#past-incidents


Let's keep an eye on this and try identifying the issue when it happens again
