### ISSUE TITLE
broken verify links

### ISSUE THREAD

**Issue by okwme** [personaelabs/creddd#29]
I found the original list of anons on [twitter](https://twitter.com/personae_labs/status/1705237623093264851) and they each have verify urls that are broken at this point.  
they are tinyurl links but resolve to the following format:
```
https://cred-frontend.vercel.app/verify?proofHash=<hash>
```
This view doesn't seem to exist on the new URL https://www.creddd.xyz/

I was able to generate a proof for one of the profiles but I don't know how to share it.

**Comment by lsankar4033** [comment]
ah, good catch! investigating this now

**Comment by lsankar4033** [comment]
I think your submissions worked (I think this was you?):
https://www.creddd.xyz/user/orangemochafrappuccino
https://www.creddd.xyz/proof/0x140ef5c875bafc672cf06fe6b9abb4687b4b0feb016c20c6d01308859d31d3ee

Good catch on the existing profiles, they got affected by a data migration; fixing them now
